"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// syntax
// let variableName : dataType[] = [];
// let variableName:Array<dataType>=[];
var arr = [1, 2, 3, 4, 5];
console.log(arr);
var superHeros = [];
superHeros.push(1);
superHeros.push(2);
console.log(superHeros);
var sp2 = [];
sp2.push(1);
sp2.push(3);
console.log(sp2);
var user1 = [];
user1.push({ name: "h", age: 25, email: "h@h.com", isActive: true });
user1.push({ name: "s", age: 25, email: "h@s.com", isActive: true });
user1.push({ name: "k", age: 25, email: "h@k.com", isActive: true });
console.log(user1);
console.log(user1[0].name);
var sp3 = [];
sp3.push([1, 2, 3]);
sp3.push([33, 32, 34]);
console.log(sp3[0]);
//Tuple
var tup = [1, "hello", true];
tup = [22, "sathvik", true];
var check;
check = ["hello", true];
var rgb = [122, 122, 122];
console.log(rgb);
